---
# defaults file for loadbalancer

nginx_timezone: UTC
nginx_apt_key: https://nginx.org/keys/nginx_signing.key
nginx_apt_keyid: ABF5BD827BD9BF62
nginx_apt_list: "deb http://nginx.org/packages/debian {{ ansible_lsb.codename }} nginx"
server_hostname: lb.example.com
package: nginx

enable_nginx_lb: false
load_balancer_is_required: false

# DNS mapping for webservers

web1: 172.31.30.177
web2: 172.31.21.251