pipeline {
  agent any
  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
      string(name: 'tag', defaultValue: 'all',  description: 'Tags to run ansible playbook against')
    }
  environment {
        cpath = '/var/lib/jenkins/workspace/ansible-config-mgt_'+"${inventory}"+'/roles'
    }
  stages {
    stage('Clone repo') {
      parallel {
        stage('Clone repo') {
          steps {
            git(branch: "${inventory}", url: 'https://github.com/Anefu/ansible-config-mgt.git')
          }
        }

        stage('Update ansible.cfg') {
          steps {
            sh ('sudo sed -i -e "/roles_path = \\/[a-z]*\\/*/a\\roles_path = $cpath" -e "/roles_path = \\/[a-z]*\\/*/d" /etc/ansible/ansible.cfg')
          }
        }
      }
    }
    

    stage('Run playbook') {
      steps {
        ansiblePlaybook(credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml', tags: "${tag}")
      }
    }

    stage('Clean up') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }

  }
}