---
# tasks file for artifactory

- name: install java 11
  apt:
    name: java-11-openjdk-devel
    state: present

- name: install java 11
  apt:
    name: 
      - wget
      - unzip
    state: present

- name: Configuring java path
  template:
    src: templates/bash-profile.j2
    dest: .bash_profile
  

- name: reload the /etc/profile
  shell: source ~/.bash_profile


- name: add the repository key to repos list
  get_url:
    url:  https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo 
    dest: /home/ubuntu/jfrog-artifactory-rpms.repo
    mode: '0755'
 
- name: Copy the downloaded file to the etc repo
  copy:
    src: /home/ubuntu/jfrog-artifactory-rpms.repo
    dest: /etc/apt.repos.d/jfrog-artifactory-rpms.repo
    remote_src: yes
    follow: yes

- name: update cache
  apt:
    update_cache: yes

- name: install artifactory
  apt:
    name: jfrog-artifactory-oss
    state: present

- name: start and enable artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
